version: "3"
services:
    models:
        build: .
        user: $USER_ID:$GROUP_ID
        ports:
            - 5678:5678
        volumes:
            - ..:/app
        depends_on:
            - postgres
        networks:
            - postgres
    postgres:
        image: postgres:15
        environment:
            - POSTGRES_USER=openslides
            - POSTGRES_PASSWORD=openslides
            - POSTGRES_DB=openslides
        networks:
            - postgres
networks:
    postgres:
