version: "3"
services:
    models:
        build: .
        user: $USER_ID:$GROUP_ID
        ports:
            - 5678:5678
        volumes:
            - ..:/app
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USER=openslides
            - POSTGRES_DB=openslides
            - PGPASSWORD=openslides

        depends_on:
            - postgres
        networks:
            - postgres
    postgres:
        build:
            context: .
            dockerfile: Dockerfile-postgres
        environment:
            - POSTGRES_USER=openslides
            - POSTGRES_PASSWORD=openslides
            - POSTGRES_DB=openslides
        networks:
            - postgres
networks:
    postgres:
